version: "3.9"


services:
  prometheus:
    # Set storage.tsdb.allow-overlapping-blocks to support injecting test data with overlapping timestamps
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-60d}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.allow-overlapping-blocks'
