apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 1m

  - name: Discourse
    type: grafana-discourse-datasource
    uid: G6gpNLBVz
    access: proxy
    orgId: 1
    url: https://forum.communityhealthtoolkit.org
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 1h
