global:
  scrape_interval: 10m
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: json_exporter
    static_configs:
      - targets: ['json-exporter:7979']
  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']
  - job_name: cht
    metrics_path: /probe
    params:
      module: [default]
    file_sd_configs:
      - files:
        - cht-instances.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: json-exporter:7979
