global:
  scrape_interval: 1m
scrape_config_files:
  - /etc/prometheus/scrape_configs/*.yml
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']
  - job_name: cht-express-metrics
    metrics_path: /api/v1/express-metrics
    scheme: "https"
    file_sd_configs:
      - files:
        - '/etc/prometheus/cht-instances.yml'
    relabel_configs:
    - source_labels: [__address__]
      regex: "(?:https?:\\/\\/|)(?:www\\.|)(.*?)(?:\\/|)$"
      target_label: instance
      replacement: "$1"
    - source_labels: [instance]
      target_label: __address__