scrape_configs:
  - job_name: postgres
    scrape_interval: 1s
    metrics_path: /probe
    file_sd_configs:
      - files:
          - '/etc/prometheus/postgres-instances.yml'
    relabel_configs:
      - source_labels: [__address__]
        regex: "(.*)"
        replacement: "postgresql://${1}"
        target_label: __param_target
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: __param_auth_module
      - target_label: __address__
        replacement: postgres-exporter:9187
